--- Removal File for the University Accomodation Office DB

--- This file removes tables with conflicting names

--- CAUTION: BACK UP ANY DATA YOU DON'T WANT TO LOSE!!!

DROP TABLE Student CASCADE CONSTRAINTS;
DROP TABLE Staff CASCADE CONSTRAINTS;
DROP TABLE Program CASCADE CONSTRAINTS;
DROP TABLE Property CASCADE CONSTRAINTS;
DROP TABLE Room CASCADE CONSTRAINTS;
DROP TABLE Kin CASCADE CONSTRAINTS;
DROP TABLE Manages CASCADE CONSTRAINTS;
DROP TABLE Lease CASCADE CONSTRAINTS;
DROP TABLE Waitlist CASCADE CONSTRAINTS;
DROP TABLE Inspection CASCADE CONSTRAINTS;
DROP TABLE Advises CASCADE CONSTRAINTS;
